version: '3.8'

services:

  init:
    image: busybox
    volumes:
      - temp:/rw
    entrypoint: ['sh', '-c', 'mkdir -p /rw/incomplete /app1/downloads /rw/database && chmod -R 777 /rw/incomplete /rw/downloads /rw/database']
    command: [ ]

  app:
    build: 
      dockerfile: Dockerfile
    volumes:
      - temp:/rw
      - ./database:/rw/database  
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    image: slskd/slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    volumes:
      - temp:/rw
    user: 1000:1000
    environment:
      APP_DIR: /app
      SLSKD_DOWNLOADS_DIR: /rw/downloads
      SLSKD_INCOMPLETE_DIR: /rw/incomplete
      SLSKD_REMOTE_CONFIGURATION: "true"
      SLSKD_SLSK_USERNAME: "ABCSlime"
      SLSKD_SLSK_PASSWORD: "Anej1234!"
    depends_on:
      - init


  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_PASSWORD: "test"
    volumes:
      - ./database:/rw/database
      - ./plugins-enabled:/var/www/html/plugins-enabled

volumes:
  temp:
